repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]
        args: ["--line-length", "119"]
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        args: ["--rcfile=.pylintrc"]
