repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: mixed-line-ending
      - id: detect-private-key

  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        files: ".*\\.py$"
        pass_filenames: true
      - id: ruff
        name: ruff (lint)
        entry: uv run ruff check
        language: system
        types: [python]
